# coding: utf-8

"""
    Trello Api

    Trello Api generated from the online documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.custom import Custom  # noqa: E501
from swagger_client.rest import ApiException


class TestCustom(unittest.TestCase):
    """Custom unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustom(self):
        """Test Custom"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.custom.Custom()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
