# coding: utf-8

"""
    Trello Api

    Trello Api generated from the online documentation  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class List(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'closed': 'bool',
        'id': 'str',
        'id_board': 'str',
        'name': 'str',
        'subscribed': 'bool'
    }

    attribute_map = {
        'closed': 'closed',
        'id': 'id',
        'id_board': 'idBoard',
        'name': 'name',
        'subscribed': 'subscribed'
    }

    def __init__(self, closed=None, id=None, id_board=None, name=None, subscribed=None):  # noqa: E501
        """List - a model defined in Swagger"""  # noqa: E501

        self._closed = None
        self._id = None
        self._id_board = None
        self._name = None
        self._subscribed = None
        self.discriminator = None

        if closed is not None:
            self.closed = closed
        if id is not None:
            self.id = id
        if id_board is not None:
            self.id_board = id_board
        if name is not None:
            self.name = name
        if subscribed is not None:
            self.subscribed = subscribed

    @property
    def closed(self):
        """Gets the closed of this List.  # noqa: E501

        Whether the list is closed (archived)  # noqa: E501

        :return: The closed of this List.  # noqa: E501
        :rtype: bool
        """
        return self._closed

    @closed.setter
    def closed(self, closed):
        """Sets the closed of this List.

        Whether the list is closed (archived)  # noqa: E501

        :param closed: The closed of this List.  # noqa: E501
        :type: bool
        """

        self._closed = closed

    @property
    def id(self):
        """Gets the id of this List.  # noqa: E501

        The ID of the list  # noqa: E501

        :return: The id of this List.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this List.

        The ID of the list  # noqa: E501

        :param id: The id of this List.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def id_board(self):
        """Gets the id_board of this List.  # noqa: E501

        The ID of the board the list is on  # noqa: E501

        :return: The id_board of this List.  # noqa: E501
        :rtype: str
        """
        return self._id_board

    @id_board.setter
    def id_board(self, id_board):
        """Sets the id_board of this List.

        The ID of the board the list is on  # noqa: E501

        :param id_board: The id_board of this List.  # noqa: E501
        :type: str
        """

        self._id_board = id_board

    @property
    def name(self):
        """Gets the name of this List.  # noqa: E501

        The name of the list  # noqa: E501

        :return: The name of this List.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this List.

        The name of the list  # noqa: E501

        :param name: The name of this List.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def subscribed(self):
        """Gets the subscribed of this List.  # noqa: E501

        Whether the member is subscribed to this list  # noqa: E501

        :return: The subscribed of this List.  # noqa: E501
        :rtype: bool
        """
        return self._subscribed

    @subscribed.setter
    def subscribed(self, subscribed):
        """Sets the subscribed of this List.

        Whether the member is subscribed to this list  # noqa: E501

        :param subscribed: The subscribed of this List.  # noqa: E501
        :type: bool
        """

        self._subscribed = subscribed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, List):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
